-- ITEMS
DROP TABLE ITEMS;
CREATE TABLE ITEMS(
    ID VARCHAR2(36 CHAR) NOT NULL,
    NAME VARCHAR2(65 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(750 CHAR) NOT NULL,
    AMOUNT_OF_STOCK INTEGER NOT NULL,
    PRICE_AMOUNT DECIMAL(38, 10) NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (ID)
);