
-- DROP TABLES
DROP TABLE ORDER_ITEMS;
DROP TABLE ORDERS;
DROP TABLE ITEMS;
DROP TABLE CUSTOMERS;

-- CREATE ITEMS
CREATE TABLE ITEMS(
    ID VARCHAR2(36 CHAR) NOT NULL,
    NAME VARCHAR2(65 CHAR) NOT NULL,
    DESCRIPTION VARCHAR2(750 CHAR) NOT NULL,
    AMOUNT_OF_STOCK INTEGER NOT NULL,
    PRICE_AMOUNT DECIMAL(38, 10) NOT NULL,
    CONSTRAINT ITEM_PK PRIMARY KEY (ID)
);

-- CREATE CUSTOMERS
CREATE TABLE CUSTOMERS(
    ID VARCHAR2(36 CHAR) NOT NULL,
    FIRSTNAME VARCHAR2(65 CHAR) NOT NULL,
    LASTNAME VARCHAR2(65 CHAR) NOT NULL,
    EMAIL_LOCAL_PART VARCHAR2(65 CHAR) NOT NULL,
    EMAIL_DOMAIN VARCHAR2(65 CHAR) NOT NULL,
    EMAIL_COMPLETE VARCHAR2(131 CHAR) NOT NULL,
    ADDRESS_STREET_NAME VARCHAR2(100 CHAR) NOT NULL,
    ADDRESS_HOUSE_NUMBER VARCHAR2(10 CHAR) NOT NULL,
    ADDRESS_POSTAL_CODE VARCHAR2(10 CHAR) NOT NULL,
    ADDRESS_COUNTRY VARCHAR2(65 CHAR) NOT NULL,
    PHONE_NUMBER VARCHAR2(65 CHAR) NOT NULL,
    PHONE_COUNTRY_CALLING_CODE VARCHAR2(10 CHAR) NOT NULL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID)
);

-- CREATE ORDERS
CREATE TABLE ORDERS(
    ID VARCHAR2(36 CHAR) NOT NULL,
    CUSTOMER_ID VARCHAR2(36 CHAR) NOT NULL,
    CONSTRAINT ORDER_PK PRIMARY KEY (ID),
    CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (ID)
);

-- CREATE ORDER_ITEMS
CREATE TABLE ORDER_ITEMS(
    ORDERED_AMOUNT INTEGER NOT NULL,
    SHIPPING_DATE DATE NOT NULL,
    ITEM_ID VARCHAR2(36 CHAR) NOT NULL,
    ITEM_PRICE_AMOUNT DECIMAL(38, 10) NOT NULL,
    ORDER_ID VARCHAR2(36 CHAR) NOT NULL
);
